using System;
using System.ComponentModel;

using DevExpress.Persistent.Base;
using DevExpress.Xpo;

namespace Xenial.Licensing.Model
{
    [Persistent("Company")]
    [DefaultClassOptions]
    public class Company : XenialLicenseBaseObject
    {
        private string name;
        private string companyGlobalId;
        private string id = Guid.NewGuid().ToString();
        private bool isAutogenerated;

        /// <summary>
        /// Initializes a new instance of the <see cref="Company"/> class.
        /// </summary>
        /// <param name="session">The session.</param>
        public Company(Session session) : base(session) { }

        /// <summary>
        /// Invoked when the current object is about to be initialized after its creation.
        /// </summary>
        public override void AfterConstruction()
        {
            base.AfterConstruction();
            CompanyGlobalId = Guid.NewGuid().ToString();
        }

        [Key(AutoGenerate = false)]
        [Persistent("Id")]
        [Size(100)]
        public string Id { get => id; set => SetPropertyValue(ref id, value); }

        [Persistent("Name")]
        public string Name { get => name; set => SetPropertyValue(ref name, value); }

        [Persistent("CompanyGlobalId")]
        public string CompanyGlobalId { get => companyGlobalId; set => SetPropertyValue(ref companyGlobalId, value); }

        [Persistent("IsAutogenerated")]
        public bool IsAutogenerated { get => isAutogenerated; set => SetPropertyValue(ref isAutogenerated, value); }

        [Association("Company-User"), Aggregated]
        public XPCollection<CompanyUser> Users => GetCollection<CompanyUser>();
    }

    [Persistent("CompanyUser")]
    public class CompanyUser : XenialLicenseBaseObject
    {
        private string name;
        private string email;
        private Company company;
        private string id;
        private bool isAutogenerated;

        /// <summary>
        /// Initializes a new instance of the <see cref="CompanyUser"/> class.
        /// </summary>
        /// <param name="session">The session.</param>
        public CompanyUser(Session session) : base(session) { }

        [Key(AutoGenerate = false)]
        [Persistent("Id")]
        [Size(100)]
        public string Id { get => id; set => SetPropertyValue(ref id, value); }

        [Persistent("Name")]
        public string Name { get => name; set => SetPropertyValue(ref name, value); }

        [Persistent("Email")]
        public string Email { get => email; set => SetPropertyValue(ref email, value); }

        [Persistent("IsAutogenerated")]
        public bool IsAutogenerated { get => isAutogenerated; set => SetPropertyValue(ref isAutogenerated, value); }

        [Persistent("CompanyId")]
        [Association("Company-User")]
        public Company Company { get => company; set => SetPropertyValue(ref company, value); }
    }
}
